// bin2inc.c
//
// convert a binary file into a assembly source data
//
// THE "BEER-WARE LICENSE" (Revision 3.1415):
// sandro AT sigala DOT it wrote this file. As long as you retain this notice you can do
// whatever you want with this stuff.  If we meet some day, and you think this stuff is
// worth it, you can buy me a beer in return.  Sandro Sigala
//
// Modified for output assembly data by Khral Steelforge.
//
// syntax:  bin2inc <input_file> <output_file>
//
// examples:
//     bin2c font.fon font.inc
//     bin2c sometext.txt sometext_txt.inc

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef PATH_MAX
#define PATH_MAX 1024
#endif

void process( const char *ifname, const char *ofname ) {
	FILE *ifile, *ofile;
	char buf[PATH_MAX], *p;
	const char *cp;
	int c, col = 1;

	ifile = fopen( ifname, "rb" );
	if ( ifile == NULL ) {
		fprintf( stderr, "cannot open %s for reading\n", ifname );
		exit( 1 );
	}
	ofile = fopen( ofname, "wb" );
	if ( ofile == NULL ) {
		fprintf( stderr, "cannot open %s for writing\n", ofname );
		exit( 1 );
	}
	if ( ( cp = strrchr( ifname, '/' ) ) != NULL ) {
		++cp;
	} else {
		if ( ( cp = strrchr( ifname, '\\' ) ) != NULL ) {
			++cp;
		} else {
			cp = ifname;
		}
	}
	strcpy( buf, cp );
	for ( p = buf; *p != '\0'; ++p ) {
		if ( !isalnum( *p ) ) {
			*p = '_';
		}
	}

	fprintf( ofile, "; %s\r\n", cp );
	fprintf( ofile, "; Generated by bin2inc\r\n\r\n" );

	fprintf( ofile, "Font\t\t\tdb\t\t" );
	while ( ( c = getc( ifile ) ) != EOF ) {
		if ( col >= 24 ) {
			fprintf( ofile, "\r\n" );
			fprintf( ofile, "\t\t\t\tdb\t\t" );
			col = 1;
		} else if ( col > 1 ) {
			fputc( ',', ofile );
		}
		fprintf( ofile, "0%.2xh", c );
		col += 5;
	}
	fprintf( ofile, "\r\n" );

	fclose( ifile );
	fclose( ofile );
}

void usage( void ) {
	fprintf( stderr, "usage: bin2inc <input_file> <output_file>\n" );
	exit( 1 );
}

int main( int argc, char **argv ) {
	while ( argc > 3 ) {
		usage( );
	}
	if ( argc != 3 ) {
		usage( );
	}
	process( argv[1], argv[2] );
	return 0;
}
