# Rajavithi Word PC 1.2 Re-Creation makefile.

!ifndef assembler
!   define assembler wasm
!endif

!ifndef c_compiler
#!   define c_compiler wcc386
!   define c_compiler wcc
!endif

!ifndef linker
!   define linker wlink
!endif

!ifndef asm_options
!   define asm_options -zq -d1
!endif

!ifndef c_options
!   define c_options -zq -d1
!endif

.extensions:
.extensions: .com .exe .lnk .obj .c .asm

.asm.obj: .AUTODEPEND
    $(assembler) $(asm_options) $[*

.c.obj: .AUTODEPEND
    $(c_compiler) $(c_options) $[*

##############################################################################
# bin2inc.exe
##############################################################################

bin2inc: .SYMBOLIC bin2inc.exe

bin2inc_objs = bin2inc.obj

bin2inc.exe: $(bin2inc_objs) bin2inc.lnk
    $(linker) @bin2inc.lnk

bin2inc.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    bin2inc
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FILE    $(bin2inc_objs)
    #@for %i in ($(bin2inc_objs)) do @%append $@ FILE    %i

##############################################################################
# codeku.com
##############################################################################

codeku: .SYMBOLIC codeku.com

codeku.com: codeku.obj codeku.lnk
    $(linker) @codeku.lnk

codeku.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codeku
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codeku.obj

##############################################################################
# codeibm.com
##############################################################################

codeibm: .SYMBOLIC codeibm.com

codeibm.com: codeibm.obj codeibm.lnk
    $(linker) @codeibm.lnk

codeibm.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    codeibm
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    codeibm.obj

##############################################################################
# reset.com
##############################################################################

reset: .SYMBOLIC reset.com

reset.com: reset.obj reset.lnk
    $(linker) @reset.lnk

reset.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    reset
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    reset.obj

##############################################################################
# rorg.com
##############################################################################

rorg: .SYMBOLIC rorg.com

rorg.com: rorg.obj rorg.lnk
    $(linker) @rorg.lnk

rorg.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rorg
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rorg.obj

##############################################################################
# rega.com
##############################################################################

rega: .SYMBOLIC rega.com

rega.com: bin2inc.exe rega.obj rega.lnk
    bin2inc rega.fon rega.inc
    $(linker) @rega.lnk

rega.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rega
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rega.obj

##############################################################################
# rvga.com
##############################################################################

rvga: .SYMBOLIC rvga.com

rvga.com: bin2inc.exe rvga.obj rvga.lnk
    bin2inc rvga.fon rvga.inc
    $(linker) @rvga.lnk

rvga.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rvga
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    rvga.obj

##############################################################################
# thaicour.com
##############################################################################

thaicour: .SYMBOLIC thaicour.com

thaicour.com: bin2inc.exe thaicour.obj thaicour.lnk
    bin2inc thaicour.fon thaicour.inc
    $(linker) @thaicour.lnk

thaicour.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    thaicour
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @%append $@ FORMAT  dos com
    @%append $@ FILE    thaicour.obj

##############################################################################
# rw.exe
##############################################################################

rw: .SYMBOLIC rw.exe

rw_objs = rw.obj libthai.obj

rw.exe: $(rw_objs) rw.lnk
    $(linker) @rw.lnk

rw.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    rw
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @for %i in ($(rw_objs)) do @%append $@ FILE    %i

##############################################################################
# demo.exe
##############################################################################

demo: .SYMBOLIC demo.exe

demo_objs = demo.obj libthai.obj

demo.exe: $(demo_objs) demo.lnk
    $(linker) @demo.lnk

demo.lnk: $(__MAKEFILES__)
    @%create $@
    @%append $@ NAME    demo
    @%append $@ OPTION  quiet, eliminate, map, show
    @%append $@ DEBUG   all
    @for %i in ($(demo_objs)) do @%append $@ FILE    %i

##############################################################################

all: bin2inc codeku codeibm reset rega rvga thaicour rw demo

clean: .SYMBOLIC
    @if exist *.com del *.com
    @if exist *.exe del *.exe
    @if exist *.lnk del *.lnk
    @if exist *.obj del *.obj
    @if exist *.map del *.map
    @if exist *.err del *.err
